include:
  remote: 'https://gitlab.com/ebarkie/gitlab-ci/raw/master/go.yml'

stages:
  - setup
  - test
  - build

build:linux:
  extends: .build
  variables:
    BIN: netaggr-linux-x86_64
    GOOS: linux
    GARCH: x86_64

build:osx:
  extends: .build
  variables:
    BIN: netaggr-osx
    GOOS: darwin
    GARCH: x86_64

build:windows:
  extends: .build
  variables:
    BIN: netaggr-win.exe
    GOOS: windows
    GARCH: x86_64
