version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - openbsd
      - windows
archives:
  - format_overrides:
    - goos: windows
      format: zip
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
brews:
  - repository:
      owner: ebarkie
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    commit_author:
      name: Eric Barkie
      email: ebarkie@users.noreply.github.com
    homepage: https://github.com/ebarkie/netaggr
    description: Network aggregator/summarizer
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
