language: go
go:
  - 1.11.x
env:
  global:
    - GO111MODULE=on
  matrix:
    - OS=darwin BIN=netaggr-osx
    - OS=linux BIN=netaggr-linux-x86_64 RUN_TESTS=true
    - OS=windows BIN=netaggr-win.exe
script:
  - if [ "$RUN_TESTS" == true ]; then
      go vet ./...;
      go test -race -v ./...;
    fi
  - GOOS=$OS GARCH=x86_64 go build -o build/$BIN
deploy:
  provider: releases
  api_key:
    secure: g+rNi71mOwBmpuUvBO5FZZCm9A3vYeyfI3Dwue/BMg3MWvZEa/Ums+IKHZLJq1LHO/9zmJYaCgddZx+zQG4dXro+2OhURtcv1o2z9HKQmmJZzvCE8Ye3GUWqAURdFqtNYXFavtN+tIPsPS7AJ5bQDGEBuD5HY80vJkPjAakpFFwdklXYYw9BRZ8HUJXLmvGXaEMczR6rsIyNUWnUIDfqOu1OTPBtRcjnfYs0YWlYBgpZbEm4Wl4OBwlCc9/MAngthyjGwuh3v3iIt8aHpCUzqdrSqodAoqHkJ0A2qA67KMuL+S8rAlK/ixf3F1rmRreodZ6HgJdF6ZSJm2b6UDiZLv55/qXoH9o7qCTSa0Vcu0feW7x0wVG/SRbkFcBOk2mVdSI+bpgIady+BiAyBPjHsYRRMNmLBrK8Ihvb30pW6hzBv3TZWArGTnn8vaxgAdfH85LtyPjMUeT/DyAY28gwQkkp5bwhdWnc8nydkc7h/ATfrhPShYxsJdIxSzF4cXqkDcSO2ky12h2IoalGo1z6tMM0tLXmk/RuvV2CUk/qkIsF5zw4Jh20MSFNWYJGyj4iy/t6rp9xPdfkB7j2VXHs/Hdkyzk93CuCnHTeWUiSO5AlY4L5Ix8Qzqx/hyT9XMfQSu7dk7EXnvLAMjffMiFNJyB5tcqsSP/zEfC6MmU3L+0=
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true
