language: go
go:
  - '1.10'
env:
  - GARCH=x86_64
script:
  - go vet ./...
  - go test -race -v ./...
  - GOOS=linux go build -o build/netaggr-linux-x86_64
  - GOOS=darwin go build -o build/netaggr-osx
  - GOOS=windows go build -o build/netaggr-win.exe
deploy:
  provider: releases
  api_key:
    secure: giIu6RD8hokLH92iCYzrxtHbahZDc60DKfJzaxNLuSscqZiBvhl8nS1DpNJMNEFrUfKFgxUgm/1w5WO9sSpWrSH6lszgPPX86Add7g+NruKvIR6EAa/TkvroUWNYt48CFToOh6pkpnIK1vdDYT0YwEOtJ6dbIc6cdm7BFfRXkwlGJo9ng3kQWdDBXTeO3ZyK1E0iAAcyt0ydnQZld4tD7q5ANgpKqaqakvLYt/QB0J1Y+bpvUHVOYNvYt3HMuYRVwBbi8IstJFkdyNdo4npHUxdLfSWQ904poNamhOEPferwW0Gak1vngw4t5vHNBzfBiJFqmml5cRb3kpkfY3Z1SPXmrFjWZLk+pjyZVgZo+KehvszHBcThS0Yop0wXHW6cwBaR2k9blE5E+XZw8B07CmW0kFgPz+7nvpHsx/GgBW3lgQxC8KGtA4whpMdtu+uOHc+vrF0HMF/ncgfjzDVll+21c1dV72Tcy1uzUOx4yF335SQqlpfCsi1YuRJ5X0ojZ6mTn9RgfwZj0EIutpsfN7vecrnQovQXbM4ohsf4a246XGO8jWUgu8PwMgr+s2PP6kFaf6wr9lLbadsyjKu5jmD61N6KmMvHXxSiKqFDsBQ0Em1kl/1HfUeeR6yrUYiOO2tjgasHdpQiuIVh4cx9f1q9QEQ+e8HV7Z188dxrKu8=
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true
