name: Release

on:
  push:
    tags:
      - v*

jobs:
  create_release:
    name: Create release

    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    strategy:
      fail-fast: false

      matrix:
        goos: [darwin, freebsd, linux, netbsd, openbsd, windows]
        goarch: [amd64]

        include:
          - goos: freebsd
            goarch: arm

          - goos: linux
            goarch: arm
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: ppc64le

          - goos: netbsd
            goarch: arm

    name: Attach ${{ matrix.goos }}/${{ matrix.goarch }}

    runs-on: ubuntu-latest

    needs: create_release

    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Go 1.14 pipeline
        id: go
        uses: ebarkie/actions/go/1.14@v1
        with:
          build_asset: true

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ steps.go.outputs.asset_path }}
          asset_name: ${{ steps.go.outputs.asset_name }}
          asset_content_type: application/zip
